sonar.projectKey=amazon-python-cicd
sonar.projectName=Amazon Python CI/CD

sonar.sources=.
sonar.tests=tests

sonar.exclusions=tests/**,venv/**,.git/**,static/**,templates/**
sonar.coverage.exclusions=tests/**

sonar.python.version=3.12
